# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               My blog
tagline:             ''
description:         ''
url:                 https://markdumke.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Markus Dumke
#  url:
#  email:

# Custom vars
#version:             1.0.0

authors:
  Markus:
    display_name: Markus Dumke
    #gravatar: 60fd5218fff6927c0ed376cce01c5460
    #email: markusdumke@gmail.com
    #github: markdumke
