
title:               markdumke Blog
tagline:             ''
description:         ''
url:                 https://markdumke.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Markus Dumke
#  url:
#  email:

# Custom vars
#version:             1.0.0

authors:
  Markus:
display_name: Markus Dumke